### ISSUE TITLE
JS call is open - its should be service based and should be included via amd

### ISSUE THREAD

**Issue by purnendudash** [Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity#1]
https://github.com/Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity/blob/b1ae08185666b71c89c14e01a40f2551918c95e8/utils.js#L17

Kindly check the references - https://moodledev.io/docs/guides/javascript#including-from-php

**Comment by cperves** [comment]
We are going to pass utils.js to an amd module to be able to use core/Ajax and correctly call the webservice.
But we can't easily transform module.js into an amd module because of the third party library ChemDoodle which is not itself amd
ChemDoodle generate a chemDoodle object which is not accessible in amd mode.
I tried to transform chemDoodle into a amd module but unsuccessfully due to path troubles and export troubles.
On top of that when we pass watchman (npx grunt watch)  on chemDoodle amd we have a ton of errors beacause it does'nt respect Moodle requirements

**Comment by cperves** [comment]
@purnendudash , 
we isolated the ajax call in a amd module using core/Ajax
But we can't call the function it in module.js (even using $PAGE->require->js_amd_call in calling php)
using import in module.js is forbidden since it is not a module
do you have an idea on how to import the amd moodle to use it in module.js
(as I said before, we can't easily change module.js into an amd module because of chemDoodle object generated by ChemDoodle external library)

**Comment by purnendudash** [comment]
This is how we should call all ajax call

https://moodledev.io/docs/guides/javascript/ajax

This is the documentations for third part library 

https://moodledev.io/general/community/plugincontribution/thirdpartylibraries#instructions

**Comment by cperves** [comment]
This is not the trouble, I know how to declare a thirdpartylibrary and how to call ajax from an amd module (I does it in another plugin I'm working on)  
the trouble is that I can't call an amd module from a standard javascript and that I can't call the chemDoodle thirparty library from a module because of the fact that the object it produces has a local scope. As I said before I tried to transform chemDoodle in Module but it failed, I am limited by the fact that I can't rewrite that external library and can't change it too much to be able to upgrade it

**Comment by cperves** [comment]
I found a solution to import amd into a traditional js
work in progress
