### ISSUE TITLE
Wrong including styles

### ISSUE THREAD

**Issue by purnendudash** [Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity#2]
https://github.com/Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity/blob/b1ae08185666b71c89c14e01a40f2551918c95e8/edit_reacsimilarity_form.php#L46

Kindly follow the JS standard - https://moodledev.io/docs/guides/javascript

**Comment by cperves** [comment]
Do you mean transforming all js in amd?
But we can't easily transform js into an amd module because of the third party library ChemDoodle which is not itself amd
ChemDoodle generate a chemDoodle object which is not accessible in amd mode.
I tried to transform chemDoodle into a amd module but unsuccessfully due to path troubles and export troubles.

**Comment by cperves** [comment]
if you mean including css in style.css, since the ChemDoodle library is external we prefer keeping it apart
On top of that ChemDoodle.css does not respect Moodle standard and when we pass watchman (npx grunt watch)  we have a ton of errors

**Comment by cperves** [comment]
I migrate all top level javascript into amd
except external library chemDoodle
