### ISSUE TITLE
Issue going to the edit question

### ISSUE THREAD

**Issue by LouisPlyer** [Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity#7]
when i want to modify a question, i got this page and these errors. 

![Clipboard - 27 février 2024 12 36](https://github.com/Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity/assets/99474110/7136d64a-503a-4ec1-aa0f-f4d2d797ec53)
![Clipboard - 27 février 2024 12 35](https://github.com/Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity/assets/99474110/91d3943a-ce3d-42aa-8a6a-64f772cf764d)

**Comment by cperves** [comment]
see a page just before this with error

**Comment by cperves** [comment]
~~an error in creation form seems to have generate malformed questions (options)
if a create a new one and edit it after it is now correct
trouble with get_question_options with older questions?~~
only on my personal dev environment since I pass from one previous version to this one to work
Trouble only concerns bad selector

**Comment by cperves** [comment]
@LouisPlyer 
I correct the selector bug and deploy it on your test server
